version: "3.3"
services:
  database:
    build: ./database
    volumes:
      - "test-db-data:/var/lib/mysql"
    networks:
      - database
    environment:
      - DB
      - DB_USER
      - DB_PASS

  mockupdb:
    build: ./mockupdb
    volumes:
      - "mockup-data:/var/lib/mysql"
    networks:
      - database
    environment:
      - A801
      - A801_USER
      - A801_PASS

  updater:
    build: ./updater
    command: ["pypy3", "-u", "/src/start.py"]
    depends_on:
      - database
      - mockupdb
    networks:
      - database
    environment:
      - DB
      - DB_IP
      - DB_USER
      - DB_PASS
      - A801
      - A801_IP
      - A801_USER
      - A801_PASS
      - BATCH_SIZE
      - PIPE_SIZE

volumes:
  test-db-data:
  mockup-data:

networks:
  database:
