version: "3.3"
services:
  database:
    build: ./database
    volumes:
      - "db-data:/var/lib/mysql"
    networks:
      - database
    environment:
      - MYSQL_DATABASE=${DB}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}

  updater:
    build: ./updater
    depends_on:
      - database
    networks:
      - database
    environment:
      - DB
      - DB_IP
      - DB_USER
      - DB_PASS
      - A801
      - A801_IP
      - A801_USER
      - A801_PASS
      - BATCH_SIZE
      - PIPE_SIZE

  redis:
    image: redis:latest
    command: [
      "/bin/sh", "-c",
      "chown -R redis /tmp/docker && redis-server /etc/redis/redis.conf"
    ]
    networks:
      - infrastructure
    volumes:
      - "redis-data:/data"
      - "./redis.conf:/etc/redis/redis.conf"
      - "redis-socket:/tmp/docker"

  auth:
    build: ./auth
    volumes:
      - "./shared:/src/shared"
      - "redis-socket:/tmp/docker"
    depends_on:
      - redis
      - database
    networks:
      - infrastructure
      - database
    environment:
      - DB
      - DB_IP
      - DB_USER
      - DB_PASS
      - INFRA_ADDR
      - INFRA_RECONNECT
      - INFRA_PING_DELAY
      - INFRA_PING_TIMEOUT
      - HASH_WORKERS=0
      - WORKERS=1

  changelogs:
    build: ./changelogs
    volumes:
      - "./shared:/src/shared"
      - "redis-socket:/tmp/docker"
    depends_on:
      - redis
      - database
    networks:
      - infrastructure
      - database
    environment:
      - DB
      - DB_IP
      - DB_USER
      - DB_PASS
      - INFRA_ADDR
      - INFRA_RECONNECT
      - INFRA_PING_DELAY
      - INFRA_PING_TIMEOUT
      - WORKERS=1

  dressroom:
    build: ./dressroom
    volumes:
      - "./shared:/src/shared"
      - "redis-socket:/tmp/docker"
    depends_on:
      - redis
    networks:
      - infrastructure
    environment:
      - INFRA_ADDR
      - INFRA_RECONNECT
      - INFRA_PING_DELAY
      - INFRA_PING_TIMEOUT
      - WORKERS=1

  lookup:
    build: ./lookup
    volumes:
      - "./shared:/src/shared"
      - "redis-socket:/tmp/docker"
    depends_on:
      - redis
      - database
    networks:
      - infrastructure
      - database
    environment:
      - DB
      - DB_IP
      - DB_USER
      - DB_PASS
      - INFRA_ADDR
      - INFRA_RECONNECT
      - INFRA_PING_DELAY
      - INFRA_PING_TIMEOUT
      - WORKERS=2

  profile:
    build: ./profile
    volumes:
      - "./shared:/src/shared"
      - "redis-socket:/tmp/docker"
    depends_on:
      - redis
      - database
    networks:
      - infrastructure
      - database
    environment:
      - DB
      - DB_IP
      - DB_USER
      - DB_PASS
      - NAME_WEBHOOK
      - INFRA_ADDR
      - INFRA_RECONNECT
      - INFRA_PING_DELAY
      - INFRA_PING_TIMEOUT
      - WORKERS=2

  router:
    build: ./router
    volumes:
      - "./shared:/src/shared"
      - "redis-socket:/tmp/docker"
    depends_on:
      - redis
    networks:
      - router
      - infrastructure
    environment:
      - INFRA_ADDR
      - INFRA_RECONNECT
      - INFRA_PING_DELAY
      - INFRA_PING_TIMEOUT
      - SESSION_KEY
      - REFRESH_KEY
      - VALIDATE_KEY
      - WORKERS=2

  nginx:
    build: ./nginx
    depends_on:
      - router
    networks:
      - router
      - frontend
    ports:
      - "80:80"

  validation:
    build: ./validation
    restart: always
    volumes:
      - "./shared:/src/shared"
      - "redis-socket:/tmp/docker"
    depends_on:
      - redis
    networks:
      - infrastructure
    environment:
      - INFRA_ADDR
      - INFRA_RECONNECT
      - FORUM_USER
      - FORUM_PASS

volumes:
  db-data:
  redis-data:
  redis-socket:

networks:
  database:
  infrastructure:
  router:
  frontend:
    external: true
